modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "ppl_utils"
version = "${version}"
displayName = "ppl_utils"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.ppl_utils]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ppl_utils]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ppl_utils]]
modId = "architectury"
type = "required"
versionRange = "[18.0.5,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "ppl_utils.mixins.json"
